# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("RAILS_DB_NAME") %>
  username: <%= ENV.fetch("RAILS_DB_USERNAME") %>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") %>
  host: <%= ENV.fetch("RAILS_DB_HOST") %>
  port: <%= ENV.fetch("RAILS_DB_PORT") %>
