title: PrivacyRequests
url: https://privacyrequests.org/
app_url: https://app.privacyrequests.org
github_url: https://github.com/privacyrequests/privacyrequests

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
